-- MySQL Script generated by MySQL Workbench
-- 12/14/16 09:43:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema istitutobancario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema istitutobancario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `istitutobancario` DEFAULT CHARACTER SET utf8 ;
USE `istitutobancario` ;

-- -----------------------------------------------------
-- Table `istitutobancario`.`Filiale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `istitutobancario`.`Filiale` ;

CREATE TABLE IF NOT EXISTS `istitutobancario`.`Filiale` (
  `idFiliale` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `città` VARCHAR(45) NULL,
  `saldo_euro` VARCHAR(45) NULL,
  PRIMARY KEY (`idFiliale`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `istitutobancario`.`Conto corrente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `istitutobancario`.`Conto corrente` ;

CREATE TABLE IF NOT EXISTS `istitutobancario`.`Conto corrente` (
  `Num_Conto` INT NOT NULL AUTO_INCREMENT,
  `Saldo_euro_positivo` DOUBLE NULL,
  `Cliente_Codice fiscale` VARCHAR(16) NULL,
  `Cliente_Filiale_idFiliale` INT NULL,
  `Filiale_idFiliale` INT NOT NULL,
  PRIMARY KEY (`Num_Conto`, `Filiale_idFiliale`),
  CONSTRAINT `fk_Conto corrente_Filiale1`
    FOREIGN KEY (`Filiale_idFiliale`)
    REFERENCES `istitutobancario`.`Filiale` (`idFiliale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Conto corrente_Filiale1_idx` ON `istitutobancario`.`Conto corrente` (`Filiale_idFiliale` ASC);


-- -----------------------------------------------------
-- Table `istitutobancario`.`Prestito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `istitutobancario`.`Prestito` ;

CREATE TABLE IF NOT EXISTS `istitutobancario`.`Prestito` (
  `Codice_cliente` INT NOT NULL,
  `Somma_euro` INT NOT NULL,
  `Codice_matricola` INT NOT NULL,
  `Codice_ufficio` INT NOT NULL,
  `Data apertura` DATE NOT NULL,
  `Data_estinzione` DATE NULL,
  `Prestitocol` VARCHAR(45) NULL,
  PRIMARY KEY (`Codice_cliente`),
  CONSTRAINT `codice_ufficio`
    FOREIGN KEY (`Codice_ufficio`)
    REFERENCES `istitutobancario`.`Filiale` (`idFiliale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `codice_ufficio_idx` ON `istitutobancario`.`Prestito` (`Codice_ufficio` ASC);


-- -----------------------------------------------------
-- Table `istitutobancario`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `istitutobancario`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `istitutobancario`.`Cliente` (
  `Codice fiscale` VARCHAR(16) NULL,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `indirizzo` VARCHAR(45) NULL,
  `numero_telefonico` VARCHAR(45) NULL,
  `Filiale_idFiliale` INT NOT NULL,
  `Prestito_Codice cliente` INT NOT NULL,
  PRIMARY KEY (`Codice fiscale`, `Filiale_idFiliale`, `Prestito_Codice cliente`),
  CONSTRAINT `fk_Cliente_Prestito1`
    FOREIGN KEY (`Prestito_Codice cliente`)
    REFERENCES `istitutobancario`.`Prestito` (`Codice_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_Prestito1_idx` ON `istitutobancario`.`Cliente` (`Prestito_Codice cliente` ASC);


-- -----------------------------------------------------
-- Table `istitutobancario`.`Cliente_has_Conto corrente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `istitutobancario`.`Cliente_has_Conto corrente` ;

CREATE TABLE IF NOT EXISTS `istitutobancario`.`Cliente_has_Conto corrente` (
  `Cliente_Codice fiscale` VARCHAR(16) NOT NULL,
  `Cliente_Filiale_idFiliale` INT NOT NULL,
  `Cliente_Prestito_Codice cliente` INT NOT NULL,
  `Conto corrente_N°Conto` INT NOT NULL,
  PRIMARY KEY (`Cliente_Codice fiscale`, `Cliente_Filiale_idFiliale`, `Cliente_Prestito_Codice cliente`, `Conto corrente_N°Conto`),
  CONSTRAINT `fk_Cliente_has_Conto corrente_Cliente1`
    FOREIGN KEY (`Cliente_Codice fiscale` , `Cliente_Filiale_idFiliale` , `Cliente_Prestito_Codice cliente`)
    REFERENCES `istitutobancario`.`Cliente` (`Codice fiscale` , `Filiale_idFiliale` , `Prestito_Codice cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Conto corrente_Conto corrente1`
    FOREIGN KEY (`Conto corrente_N°Conto`)
    REFERENCES `istitutobancario`.`Conto corrente` (`Num_Conto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_has_Conto corrente_Conto corrente1_idx` ON `istitutobancario`.`Cliente_has_Conto corrente` (`Conto corrente_N°Conto` ASC);

CREATE INDEX `fk_Cliente_has_Conto corrente_Cliente1_idx` ON `istitutobancario`.`Cliente_has_Conto corrente` (`Cliente_Codice fiscale` ASC, `Cliente_Filiale_idFiliale` ASC, `Cliente_Prestito_Codice cliente` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
